### ISSUE TITLE
在Android10(EMUI10.1/MagicUI3.1)桌面上显示图标

### ISSUE THREAD

**Issue by DawningW** [Dawncraft/Dawn-Desktop-Addons#1]
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: FATAL EXCEPTION: main
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: Process: com.huawei.android.launcher, PID: 5339
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: java.lang.SecurityException: Attempt to launch activity without  category Intent.CATEGORY_LAUNCHER ComponentInfo{io.github.dawncraft.desktopaddons/android.app.AppDetailsActivity}
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2071)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1987)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.content.pm.ILauncherApps$Stub$Proxy.startActivityAsUser(ILauncherApps.java:1020)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.content.pm.LauncherApps.startMainActivity(LauncherApps.java:563)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.appwidget.AppWidgetHostView.onDefaultViewClicked(AppWidgetHostView.java:711)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.appwidget.AppWidgetHostView.lambda$ab7zr5jJn3-7TaWMNA8VPkK4SdQ(Unknown Source:0)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.appwidget.-$$Lambda$AppWidgetHostView$ab7zr5jJn3-7TaWMNA8VPkK4SdQ.onClick(Unknown Source:2)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.view.View.performClick(View.java:7216)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7190)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.view.View.access$3500(View.java:827)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27663)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8349)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.startActivityAsUser(libmapleservices.so:16227460)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.content.pm.ILauncherApps$Stub.onTransact(libmapleframework.so:4257116)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(libmapleframework.so:5521040)
09-12 20:14:45.494 10079  5339  5339 E AndroidRuntime: 	at android.os.Binder.execTransact(libmapleframework.so:5520252)

**Comment by DawningW** [comment]
可在Android10(EMUI11/MagicUI4.0)上复现, 目前尚未找到解决方案

**Comment by DawningW** [comment]
另外在首次添加桌面小部件后点击空白位置也会报这个错误, 但是再点就不会报错了

**Comment by DawningW** [comment]
该问题已解决
原因是从Android 3.0起点击小部件默认会跳转至应用主Activity
而该应用无主Activity
解决方案是给根layout设个点击

但是仍然不知道为何桌面上会显示图标

**Comment by DawningW** [comment]
桌面显示图标是Android10后加入的特性, 无法隐藏
已通过activity-alias实现显示/隐藏桌面图标(仅对Android10以下有效)
感谢QNotified
